### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jaggerdelagenti** [tonefolder/discogs-angular2-app#1]
i have this errors when i try to login....

GET http://localhost:4200/api/user/ 404 (Not Found) 

error_handler.js:54 EXCEPTION: Unexpected token < in JSON at position 0

SyntaxError: Unexpected token < in JSON at position 0

**Comment by tonefolder** [comment]
What is your discogs user name?

**Comment by tonefolder** [comment]
This looks like an error that would occur if the server is not running.  Are you running the server when you try to log in?

I'm going to make sure an error message pops up in the browser when this happens.

**Comment by tonefolder** [comment]
this is committed.

**Comment by jaggerdelagenti** [comment]
hi.. the server is running with npm start....

**Comment by tonefolder** [comment]
I merged a fix yesterday.  Please pull the latest code and try again.
FYI - the "login" isn't really a real login.  it is just telling the server which discogs user's public data to access.
In the future there will be a real login that allows you to use you actual discogs account 
See here: #6
